name: "Terraform CICD - AWS Infra"

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  # Verbosity setting for Terraform logs
  TF_LOG: WARN
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  terraform-dev:
    name: "Terraform Infra CICD Dev"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: dev

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Terraform init dev
        id: init
        run: terraform init -reconfigure -backend-config=bucket=$BUCKET_TF_STATE

      # Quality checks
      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate
      
      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file=env/dev.tfvars -out=dev.tfplan -no-color -input=false
        continue-on-error: true
